package kr.co.reyonpharm.models;

import lombok.Getter;
import lombok.Setter;

public class SalaryInfo {
	private @Getter @Setter String region;
	private @Getter @Setter String mail;
	private @Getter @Setter String yymm;
	private @Getter @Setter String yyyy;
	private @Getter @Setter String mm;
	private @Getter @Setter String payDate;
	private @Getter @Setter String sabun;
	private @Getter @Setter String kname;
	private @Getter @Setter String deptCode;
	private @Getter @Setter String deptName;
	private @Getter @Setter String grade;
	private @Getter @Setter String hobong;
	private @Getter @Setter String payType;
	private @Getter @Setter String workTypetxt;
	private @Getter @Setter String bonusRate;
	private @Getter @Setter String otNight;
	private @Getter @Setter String otSunday;
	private @Getter @Setter String payTotal;
	private @Getter @Setter String subTotal;
	private @Getter @Setter String payRemain;
	private @Getter @Setter String aa01;
	private @Getter @Setter String aa02;
	private @Getter @Setter String aa03;
	private @Getter @Setter String aa04;
	private @Getter @Setter String aa05;
	private @Getter @Setter String aa06;
	private @Getter @Setter String aa07;
	private @Getter @Setter String aa08;
	private @Getter @Setter String aa09;
	private @Getter @Setter String aa10;
	private @Getter @Setter String aa11;
	private @Getter @Setter String aa12;
	private @Getter @Setter String aa13;
	private @Getter @Setter String bb01;
	private @Getter @Setter String bb02;
	private @Getter @Setter String bb03;
	private @Getter @Setter String bb04;
	private @Getter @Setter String bb05;
	private @Getter @Setter String bb06;
	private @Getter @Setter String bb07;
	private @Getter @Setter String bb08;
	private @Getter @Setter String bb09;
	private @Getter @Setter String bb10;
	private @Getter @Setter String bb11;
	private @Getter @Setter String cc01;
	private @Getter @Setter String cc02;
	private @Getter @Setter String cc03;
	private @Getter @Setter String cc04;
	private @Getter @Setter String mailGbn;
	private @Getter @Setter String payGb;
	private @Getter @Setter int isSales;
	private @Getter @Setter String saupcode;
}
